### ISSUE TITLE
Merge multiple lines into one

### ISSUE THREAD

**Issue by lithiumoxide** [creadak/creabot#105]
The following could be combined into two lines for easier reading.

    TURN 48: creadak's turn.
    180 seconds on the clock
    creadak has played RED 4!
    creadak has 3 cards left!

becomes...

    TURN 48: creadak's turn. 180 seconds on the clock
    creadak has played RED 4! creadak has 3 cards left!

This also removes too many bells and flashes on the terminal.

**Comment by creadak** [comment]
Excellent suggestion, implemented.
