### ISSUE TITLE
Game tries to read config after player wins

### ISSUE THREAD

**Issue by creadak** [creadak/creabot#116]

**Comment by creadak** [comment]
Not fixed, happened again. Stack trace below.

In game.nextTurn()
/home/creadak/sources/creabot-dev/plugin_code/uno/app/models/game.js:130
    var seconds = Math.max(60, (60 * self.config.gameOptions.turnMinutes) -
                                                ^
TypeError: Cannot read property 'gameOptions' of undefined
    at self.turnTimer (/home/creadak/sources/creabot-dev/plugin_code/uno/app/models/game.js:130:49)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by butlerx** [comment]
timers keep going even after the bot has stopped the game

**Comment by creadak** [comment]
Done. Problem was clearTimeout(self.turnTimeout) instead of clearInterval(self.turnTimeout) in self.nextTurn.
