### ISSUE TITLE
Letters rounds should have a minimum of 3 vowels

### ISSUE THREAD

**Issue by creadak** [creadak/creabot#76]

**Comment by creadak** [comment]
cmdArgs isn't defined in game.js

Also want the amount of vowels you have to have configurable

**Comment by butlerx** [comment]
i ve no idea why i wrote it like that

**Comment by creadak** [comment]
S'cool :) Should be fixed now any way, and configurable to boot!

**Comment by butlerx** [comment]
Did you mean to reopen this?
